name: test_install_npm_packages
on:
  workflow_dispatch:
    inputs:
      names:
        description: names
        required: true
  # push:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      - run: npm install ${{ inputs.names }}
      - run: |
          packages="${{ inputs.names }}"

          for package in $packages; do
            echo "Package: $package"
            npm show $package
            echo "--------------------------------"
          done